paths:
  /api/products:
    get:
      summary: Obtiene todos los productos de la App.
      tags: 
        - Products
      responses:
        "200":
          description: respuesta exitosa! se retorna un arreglo con los productos.
          content:  
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "400":
          description: Se envio un dato no valido.
        "500":
          description: Error inesperado en el servidor, no se pudo manejar el proceso.

components:
  schemas:
    Product:
      type: object
      properties:
        id: 
          type: String
          description: Id del proucto.
        title: 
          type: String
          description: titulo del producto.
        description: 
          type: String
          description: descripcion del usuario.
        price: 
          type: Number
          description: precio del producto.
        thumbnail:
          type: String
          description: link de imagen del producto.
        stock: 
          type: Number
          description: stock disponible del producto.
        category: 
          type: String
          description: categoria del producto.
        owner:
          type: ObjectId
          description: usuario dueño del carrito.
      example:
        id: H14
        title: Producto de prueba 1
        description: Descripcion de prueba 1
        price: 1234
        thumbnail: www.imagendeprueba.com
        stock: 50
        category: Helado
        owner: ObjectId("655eafee18d63f2d8e18f8c5")
    